default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Savings_development
  host: 127.0.0.1

test:
  <<: *default
  database: Savings_test

production:
  <<: *default
  database: Savings_production
  username: Savings
  password: <%= ENV['SAVINGS_DATABASE_PASSWORD'] %>
